---
title: "Project Head and Neck Cancer"
author: "Nils Mechtel, Tobias Hub, Niklas Urbanek, Pascal Poc"
date: "6 Mai 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load dataset
allDepMapData = readRDS("DepMap19Q1_allData.RDS")

##Creation of sub matrices
expression = allDepMapData[["expression"]]
copynumber = allDepMapData[["copynumber"]]
mutation = allDepMapData[["mutation"]]
kd.ceres = allDepMapData[["kd.ceres"]]
kd.prob = allDepMapData[["kd.prob"]]
annotation = allDepMapData[["annotation"]]

##Defining a criterion to reducing the patients to head and neck cancer patients
anno.HNC = annotation[which(annotation$Primary.Disease == "Head and Neck Cancer"), ]
ID = anno.HNC$DepMap_ID

##Filtering of sub matrices by primary disease "Head and neck cancer"
expression = expression[ , which(colnames(expression) %in% ID)]
copynumber = copynumber[ , which(colnames(copynumber) %in% ID)]
kd.ceres = kd.ceres[ , which(colnames(kd.ceres) %in% ID)]
kd.prob = kd.prob[ , which(colnames(kd.prob) %in% ID)]
mutation = mutation[ID]

###notes: no missing values

##First steps of descriptive statistics

###Range of data
range(kd.ceres)
###Example EGFR
summary(esgeneT$EGFR)

##Definition of a compare group
comparegroup = allDepMapData[["kd.ceres"]]
comparegroup = comparegroup[,- which(colnames(kd.ceres) %in% ID)]

##Are there genes that tend to be more essential in HNC?
esgene1 = kd.ceres[-which(rowMeans(kd.ceres)> rowMeans(comparegroup)),]

##Transposition of matrix esgene1
esgeneT <- as.data.frame(t(esgene1))

##Boxplot of 10 genes

boxplot(esgeneT[1:10], xlab = "gene", horizontal = F)
abline(col = c("blue", "red", "black", "orange"), 
    lty = 2)

